// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core';

export {};

declare module '@vue/runtime-core' {
    export interface GlobalComponents {
        FrameView: typeof import('./src/layout/frame-view/index.vue')['default'];
        RouterLink: typeof import('vue-router')['RouterLink'];
        RouterView: typeof import('vue-router')['RouterView'];
        Tabbar: typeof import('./src/layout/tabbar/index.vue')['default'];
        VanButton: typeof import('vant/es')['Button'];
        VanIcon: typeof import('vant/es')['Icon'];
        VanTabbar: typeof import('vant/es')['Tabbar'];
        VanTabbarItem: typeof import('vant/es')['TabbarItem'];
        VanTag: typeof import('vant/es')['Tag'];
    }
}
