/*
 * @Descripttion:
 * @version:
 * @Author: zhoukai
 * @Date: 2022-11-22 11:22:02
 * @LastEditors: zhoukai
 * @LastEditTime: 2022-11-22 11:22:25
 */
// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core';

export {};

declare module '@vue/runtime-core' {
    export interface GlobalComponents {
        RouterLink: typeof import('vue-router')['RouterLink'];
        RouterView: typeof import('vue-router')['RouterView'];
        VanIcon: typeof import('vant/es')['Icon'];
        VanTabbar: typeof import('vant/es')['Tabbar'];
        VanTabbarItem: typeof import('vant/es')['TabbarItem'];
        VanTag: typeof import('vant/es')['Tag'];
    }
}
